/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cppmult.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(461cde4498feac569edbe8d7bcc0db25)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bindjulia/cppmult.h>
// pydoc.h is automatically generated in the build directory
#include <cppmult_pydoc.h>

void bind_cppmult(py::module& m)
{

    using cppmult    = ::gr::bindjulia::cppmult;


    py::class_<cppmult, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cppmult>>(m, "cppmult", D(cppmult))

        .def(py::init(&cppmult::make),
           D(cppmult,make)
        )
        



        ;




}








